name: Bug Report
description: Create a bug report with priority and screen dropdowns
title: "[BUG]"
labels: bug
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority of the bug
      options:
        - High
        - Medium
        - Low

  - type: dropdown
    id: screen
    attributes:
      label: Screen
      description: Select the screen related to the bug
      options:
        - Overview
        - Func & Unit
        - User Mgmt
        - Global Question
        - Local Question
        - Run
        - New Runs
        - Run Details
        - List Assessment
        - Assessment Ans
        - Action Plan
        - Action Details
        - End User Ans
        - End User Questions
